---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      repo: registry.cthulhuden.com/transmission-proxy
      registry: registry.cthulhuden.com
      pull_image: true
      auto_tag: true
      username: { from_secret: docker-username }
      password: { from_secret: docker-password }
      platforms: [linux/amd64, linux/arm64/v8]

trigger:
  event:
    - tag

---
kind: pipeline
type: docker
name: test

steps:
  - name: dry-build
    image: plugins/docker
    settings:
      repo: registry.cthulhuden.com/transmission-proxy-dev
      pull_image: true
      dry_run: true

trigger:
  event:
    - push
