name: Test for docker build

on:
  push:
    branches: ["**"]

jobs:
  check:
    uses: ./.gitea/workflows/check.yaml
  build:
    runs-on: ubuntu-20.04 # cant run latest/22.04 on my old debian sadly
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: "network=${{ vars.BUILD_NETWORK }}"
      - name: Build
        uses: docker/build-push-action@v5
        with:
          pull: true
